dna = input ("Enter DNA sequence: ")
dna = dna.upper()
length = len(dna)
A_count = dna.count("A")
T_count = dna.count("T")
C_count = dna.count("C")
G_count = dna.count("G")
print("\nResults:")
print("DNA= " + dna)
print("Length= " , length)
print("A= " , A_count)
print("T= " , T_count)
print("C= " , C_count)
print("G= " , G_count)
